export SECRETS_FILE="../secrets.sh"

source ${SECRETS_FILE}

export SUBSCRIPTION_ID=${SECRET_SUBSCRIPTION_ID}
export TENANT_ID=${SECRET_TENANT_ID}
export LOCATION=eastus2

export RESOURCE_GROUP_NAME=${ENVIRONMENT}
export STORAGE_ACCOUNT_PREFIX=${ENVIRONMENT}
export PUBLIC_IP_NAME=${ENVIRONMENT}-ip
export VIRTUAL_NETWORK_NAME=${ENVIRONMENT}-network
export BOSH_SUBNET_NAME=${ENVIRONMENT}-bosh
export CF_SUBNET_NAME=${ENVIRONMENT}-cf
export DOMAIN_LABEL=${ENVIRONMENT}-domain
export ACTIVE_DIRECTORY_APPLICATION_NAME=${ENVIRONMENT}-bosh-ad-name
export OUTPUT_DIR="$(pwd)/output/${ENVIRONMENT}"
export SSH_PRIVATE_CERTIFICATE_FILE="${OUTPUT_DIR}/bosh.key"
export SSH_PUBLIC_CERTIFICATE_FILE="${SSH_PRIVATE_CERTIFICATE_FILE}.pub"

export JUMPBOX_NIC=${ENVIRONMENT}-jumpbox-nic
export JUMPBOX_NAME="jumpbox1"
export JUMPBOX_USER=vcap
export JB_SUBNET_NAME=jumpbox1
export JB_IMAGE='Canonical:UbuntuServer:14.04.2-LTS:latest'
export JB_VM_SIZE=Standard_D2_v2
