source ./secrets.sh

export SUBSCRIPTION_ID=${SECRET_SUBSCRIPTION_ID}
export TENANT_ID=${SECRET_TENANT_ID}
export LOCATION=westus
export STORAGE_TYPE=lrs

export RESOURCE_GROUP_NAME=${ENVIRONMENT}-resource
export STORAGE_ACCOUNT_NAME=${ENVIRONMENT}cfhosted2016
export PUBLIC_IP_NAME=${ENVIRONMENT}-ip
export VIRTUAL_NETWORK_NAME=${ENVIRONMENT}-network
export BOSH_SUBNET_NAME=${ENVIRONMENT}-bosh
export CF_SUBNET_NAME=${ENVIRONMENT}-cf
export DOMAIN_LABEL=${ENVIRONMENT}-domain
export ACTIVE_DIRECTORY_APPLICATION_NAME=${ENVIRONMENT}-bosh-ad-name
export OUTPUT_DIR="./output/${ENVIRONMENT}"

