source ./secrets.sh

export SUBSCRIPTION_ID=${SECRET_SUBSCRIPTION_ID}
export TENANT_ID=${SECRET_TENANT_ID}
export LOCATION=westus
export STORAGE_TYPE=lrs

export RESOURCE_GROUP_NAME=${ENVIRONMENT}-resource
export STORAGE_ACCOUNT_NAME=${ENVIRONMENT}cfhosted2016
export PUBLIC_IP_NAME=${ENVIRONMENT}-ip
export VIRTUAL_NETWORK_NAME=${ENVIRONMENT}-network
export BOSH_SUBNET_NAME=${ENVIRONMENT}-bosh
export CF_SUBNET_NAME=${ENVIRONMENT}-cf
export DOMAIN_LABEL=${ENVIRONMENT}-domain
export ACTIVE_DIRECTORY_APPLICATION_NAME=${ENVIRONMENT}-bosh-ad-name

# Load balancer setups
export LOAD_BALANCER_NAME=logsearch_ingestor
export FRONTEND_SUBNET_NAME=load-balancer
export FRONTEND_INTERNAL_IP=10.10.253.10
export FRONTEND_POOL_NAME=${LOAD_BALANCER_NAME}_frontpool
export BACKEND_POOL_NAME=${LOAD_BALANCER_NAME}_backpool
export LOAD_BALANCER_RULE_NAME=${LOAD_BALANCER_NAME}_rule
export LOAD_BALANCER_PROBE_NAME=${LOAD_BALANCER_NAME}_probe

