load-balancers:
  internal:
    - name: logsearch_ingestor
      frontend_subnet_name: load-balancer
      frontend_internal_ip: 10.10.253.10
      frontend_port: 5514
      backend_port: 5514
      probe_port: 1936
      probe_interval: 400
      probe_fail_count: 2

    - name: mysql_proxy
      frontend_subnet_name: load-balancer
      frontend_internal_ip: 10.10.253.20
      frontend_port: 3306
      backend_port: 3306
      probe_port: 1936
      probe_interval: 15
      probe_fail_count: 2

  external:
    - name: concourse
      public_ips: concourse_eip
    - name: haproxy
      public_ips: haproxy_eip
    - name: login_wildcard
      public_ips: login_wildcard_eip
