storage_accounts:
  - name: jumpbox1
    type: lrs
  - name: bosh
    type: lrs
  - name: concourse
    type: plrs
  - name: conccourselrs
    type: lrs
  - name: mysqlsa
    type: plrs
  - name: cf
    type: plrs
  - name: diego
    type: plrs
