storage_accounts:
  - name: default
    type: lrs
  - name: bosh
    type: lrs
  - name: concourse
    type: plrs
  - name: mysqlsa
    type: plrs
  - name: cf
    type: plrs
  - name: diego
    type: plrs
